### ISSUE TITLE
[Problem Report] Device not ready 

### ISSUE THREAD

**Issue by d3ward** [aleksey-hoffman/sigma-file-manager#82] opened 2021-05-29 12:01 UTC
## Problem:
After installed , i can't access any folder or file with Sigma , like my HDD doesn't exist 

## Log :
Error: Error: EISDIR, Device not ready .
 'D:/'
    at o.fetchStorageDevices (app://./index.bundle.js:1:48802)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async o.mounted (app://./index.bundle.js:1:22620)

## System info:
- **App version**: `1.0.0` 
- **Operating System**: `x64 | Windows 10`

**Comment by aleksey-hoffman** [comment] 2021-05-29 12:14
The problem is fixed in v1.1.0. 
You can click "Check for update now" in the settings
Or download the release manually here: https://github.com/aleksey-hoffman/sigma-file-manager/releases

**Closed by aleksey-hoffman** 2021-05-29 12:14 UTC
Labels: bug
