### ISSUE TITLE
[Problem report] the program can be opened several times

### ISSUE THREAD

**Issue by leorossi2005** [aleksey-hoffman/sigma-file-manager#56] opened 2021-05-27 17:59 UTC
## System info:
- **App version**: 1.1.0
- **Operating System**: Win10 Pro x64 21H1

## Problem:
If Sigma is opened through its .exe Sigma can be started several times and you can have, for example, 100 Sigma open in the background.

**Comment by OfficialEsco** [comment] 2021-05-27 18:48
Duplicate of #7

**Comment by Ansh4011** [comment] 2021-05-29 09:55
> ## System info:
> * **App version**: 1.1.0
> * **Operating System**: Win10 Pro x64 21H1
> 
> ## Problem:
> If Sigma is opened through its .exe Sigma can be started several times and you can have, for example, 100 Sigma open in the background.

It depends on how you open it(via .exe or system tray) and how have you configured the settings! I have made a video to resolve this problem! Check this for reference-->  https://github.com/aleksey-hoffman/sigma-file-manager/issues/7#issuecomment-850777639

**Comment by aleksey-hoffman** [comment] 2021-06-07 23:05
fixed https://github.com/aleksey-hoffman/sigma-file-manager/commit/50643ef7d6493a0ae089a38616dea620fb6a3641

**Closed by aleksey-hoffman** 2021-06-07 23:05 UTC
