### ISSUE TITLE
Doesnt find any drives

### ISSUE THREAD

**Issue by thedatabug** [aleksey-hoffman/sigma-file-manager#10] opened 2021-05-25 13:41 UTC
## System info:
- **App version**: 1.0.0 -->
- **Operating System**: Windows 10 Pro (19042.985)

## Problem
Error: Error: EISDIR, The device is not ready.
 'T:/'
    at o.fetchStorageDevices (app://./index.bundle.js:1:48802)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async o.mounted (app://./index.bundle.js:1:22620)

**Comment by OfficialEsco** [comment] 2021-05-25 13:46
Welcome to GitHub, remember to Search and look at other cases :)
Duplicate of #1

**Closed** 2021-05-26 11:32 UTC

**Comment by aleksey-hoffman** [comment] 2021-05-26 12:03
Thank you. The problem is fixed.
I will release the update today.
