### ISSUE TITLE
i have not second file manger , i always sigma

### ISSUE THREAD

**Issue by newyorkthink** [aleksey-hoffman/sigma-file-manager#268] opened 2023-07-11 15:11 UTC
### Is there an existing issue for this?

- [X] I have searched the opened issues

### Problem description

so, when i use sigma , i cannot draw picture or videos to sigma , because i just one file manger sigma,.

i try open two sigma appimage, is auto close

![image](https://github.com/aleksey-hoffman/sigma-file-manager/assets/87791643/69b26014-d267-4e19-9162-558eb81c3cff)

and i restart sigma ,the picture not show , i always re-selected it

### Steps to reproduce

1. 

### Environment

- OS: kali linux
- App version: 1.7

**Comment by aleksey-hoffman** [comment] 2023-07-11 19:53
Thanks, the fix for this is planned for the next update

**Comment by aleksey-hoffman** [comment] 2023-07-14 14:25
Duplicate of #17

**Closed by aleksey-hoffman** 2023-07-14 14:25 UTC
Labels: bug
