### ISSUE TITLE
[Problem Report] Device not ready error

### ISSUE THREAD

**Issue by sumitsaurabh927** [aleksey-hoffman/sigma-file-manager#38] opened 2021-05-26 05:52 UTC
## Issue details:
* Device not ready error and laggy app
## System info:
- App version: 1.0.0 
- Operating System: x64 | Windows 10 

## Problem:
* App gives error with the following code whenever started :
> Error: Error: EISDIR, The device is not ready. 'E:/' at o.fetchStorageDevices (app://./index.bundle.js:1:48802) at processTicksAndRejections (internal/process/task_queues.js:93:5) at async o.mounted (app://./index.bundle.js:1:22620)
* when the app is closed, it auto scrolls a workspace (virtual homescreens) left.
* Very unresponsive. Takes several seconds to open any folder.
![Screenshot (264)](https://user-images.githubusercontent.com/62152915/119609039-8f6f6e00-be14-11eb-9031-a735cd3bee06.png)

**Comment by OfficialEsco** [comment] 2021-05-26 07:38
Duplicate of #1

**Comment by sumitsaurabh927** [comment] 2021-05-26 10:09
Just saw it, sorry!

**Comment by OfficialEsco** [comment] 2021-05-26 10:13
I don't think the maintainer care too much about duplicates atm tho 😄 
Your second problem might be a new issue tho, the 3rd seems like a side effect of the first issue

**Comment by sumitsaurabh927** [comment] 2021-05-26 10:17
I was and am super excited for this, saw it last night and installed it first thing in the morning 😅
Too bad it doesn't work properly but super pumped for where this could go!

**Comment by aleksey-hoffman** [comment] 2021-05-26 12:37
Thank you. The problem is fixed.
I will release the update today.

**Closed by aleksey-hoffman** 2021-05-26 12:37 UTC

**Comment by sumitsaurabh927** [comment] 2021-05-26 15:02
Thanks for the amazing work! 🙂
