### ISSUE TITLE
Thumbnails doesn't show

### ISSUE THREAD

**Issue by danquijote** [aleksey-hoffman/sigma-file-manager#241] opened 2023-05-01 16:00 UTC
### Is there an existing issue for this?

- [X] I have searched the opened issues

### Problem description

Can't see thumbnails for image files.

### Steps to reproduce

1.  Open any folder with image files.

### Environment

- OS: Windows 11
- App version: latest

**Comment by aleksey-hoffman** [comment] 2023-05-02 06:06
Duplicate of #227

**Closed by aleksey-hoffman** 2023-05-02 06:06 UTC
Labels: bug
