### ISSUE TITLE
[Problem Report] Possible issue with OneDrive: steady "flashing" of images.

### ISSUE THREAD

**Issue by jala528** [aleksey-hoffman/sigma-file-manager#20] opened 2021-05-25 16:51 UTC
## System info:
- **App version**: 1.0.0
- **Operating System**: Windows10 v.21H1 build 19043.985

## Problem:

Image files in my Pictures directory "flash".  Interrupts and closes dropdown menus as well. Doesn't appear to happen on directories that don't contain images. 

https://user-images.githubusercontent.com/60282637/119536565-13a2f200-bd3e-11eb-99ac-1d56d3435529.mp4

**Comment by thebluedev** [comment] 2021-05-25 17:19
Steps to reproduce?

This does not seem to happen on my PC, even when refreshing.

**Comment by aleksey-hoffman** [comment] 2021-05-25 17:25
Is it only happening in the OneDrive directory?
I think the directory is getting automatically refreshed over and over because OneDrive is periodically updating some meta data

**Comment by thebluedev** [comment] 2021-05-25 17:36
This does not happen even in the OneDrive directory for me.

**Comment by aleksey-hoffman** [comment] 2021-05-25 17:42
@thebluedev good to know, so it's not that

Hmm. Not sure what's happening there
Could you press `CTRL+ SHIFT+ I` shortcut and check if you see any errors in the `console` tab there?

**Comment by aleksey-hoffman** [comment] 2022-08-10 16:01
Fixed in 7dcc834

**Closed by aleksey-hoffman** 2022-08-10 16:01 UTC
Labels: bug, good first issue
