### ISSUE TITLE
Problem: No Drives show up; Windows

### ISSUE THREAD

**Issue by Joester202** [aleksey-hoffman/sigma-file-manager#36] opened 2021-05-26 01:38 UTC
Error: Error: EISDIR, The device is not ready.
 'E:/'
    at o.fetchStorageDevices (app://./index.bundle.js:1:48802)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async o.mounted (app://./index.bundle.js:1:22620)

**Comment by krsagarts** [comment] 2021-05-26 03:41
Yep...same for me

**Comment by lukasong** [comment] 2021-05-26 03:57
+1

**Comment by OfficialEsco** [comment] 2021-05-26 07:37
Duplicate of #1

**Comment by aleksey-hoffman** [comment] 2021-05-26 12:26
Thank you. The problem is fixed.
I will release the update today.

**Closed by aleksey-hoffman** 2021-05-26 12:26 UTC
