### ISSUE TITLE
[Problem report] Setting the app to minimize to tray and keep memory does not "work" 

### ISSUE THREAD

**Issue by thebluedev** [aleksey-hoffman/sigma-file-manager#41] opened 2021-05-26 07:34 UTC
## System info:
- **App version**: ` 1.0.0`
- **Operating System**: `x64 | Windows 10`

## Problem:

Close and open the app from any shortcut.

Doing so will minimize when "closing" it but opening  the app from the start menu or a shortcut will create a new instance and will not open the already cached/saved instance leading to this

![image](https://user-images.githubusercontent.com/73629408/119604321-79f64600-be0c-11eb-8cfd-cbed1308f181.png)

And this

![image](https://user-images.githubusercontent.com/73629408/119604565-e96c3580-be0c-11eb-8ad0-3d4daeebda51.png)

The only way AFAIK to open the cached/saved instance is to go all the way to the system tray (above image) and then right click and click open app window

And the shortcut `ctrl+shift+space` only seems to work if the last app to be in focus was sigma.

## Fix

I'm not very experienced but here are a few suggestions.

1. allow only one instance when set to minimize to tray and keep memory
2. minimize to taskbar?

**Comment by OfficialEsco** [comment] 2021-05-26 07:43
Duplicate of #7

**Comment by aleksey-hoffman** [comment] 2021-06-07 23:04
fixed https://github.com/aleksey-hoffman/sigma-file-manager/commit/50643ef7d6493a0ae089a38616dea620fb6a3641

**Closed by aleksey-hoffman** 2021-06-07 23:04 UTC
