### ISSUE TITLE
PDF Quickview

### ISSUE THREAD

**Issue by Ansh4011** [aleksey-hoffman/sigma-file-manager#144] opened 2021-09-06 08:01 UTC
### Is there an existing issue for this?

- [X] I have searched the opened issues

### Problem description

Hi, I really personally like this new quickview feature, but I realised that apparently it is not working with pdf files, it just shows an empty grey screen. Have a look -
![image](https://user-images.githubusercontent.com/84930340/132181561-60f9c13c-6484-4614-80a8-902fcad4b343.png)

### Steps to reproduce

1. Initiate SFM.
2. Select any pdf file.
3. Now press the space button for a quick view.

### Environment

- OS: Windows 10 21H1
- App version: 1.4.0

**Comment by Ansh4011** [comment] 2021-09-06 08:17
Btw, is it possible to get options such as at which quality we want to download videos (suppose from youtube, only for testing purposes). This would be really helpful. Thanks!

**Comment by aleksey-hoffman** [comment] 2021-09-06 09:35
Thank you, I'm aware of the problem with PDF preview. The issue is caused by Electron, they changed something and broke it.

**Comment by aleksey-hoffman** [comment] 2021-09-06 09:36
> options such as at which quality we want to download videos

Please open a separate issue for this

**Comment by Ansh4011** [comment] 2021-09-06 09:46
> I'm aware of the problem..... and broke it.

Oh, okay! No worries. 
> Please open a separate issue for this

Sure

**Comment by aleksey-hoffman** [comment] 2022-08-08 13:35
Fixed in 6740b39

**Closed by aleksey-hoffman** 2022-08-08 13:35 UTC
Labels: bug

**Comment by Ansh4011** [comment] 2022-08-08 13:47
Awesome.... Hope you are doing great bro. Much excited for this release! All the best 👍

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Ansh4011** [comment] 2022-10-22 20:00
Hey Aleksey, how have you been mate?
Congrats on 1k stars 😄🤟

**Comment by aleksey-hoffman** [comment] 2022-10-23 11:39
@Ansh4011 hey Ansh! Thank you :) 
I'm doing fine. How are you?

**Comment by Ansh4011** [comment] 2022-10-25 19:25
@aleksey-hoffman Doing well too, thanks :).
