### ISSUE TITLE
an error message at startup, sigma show off and run normally afterwards

### ISSUE THREAD

**Issue by ted1958** [aleksey-hoffman/sigma-file-manager#47] opened 2021-05-26 14:58 UTC
Hi,
Copy/paste the  message above :
Error: Error: EISDIR, Le pÃ©riphÃ©rique nâest pas prÃªt.
 'H:/'
    at o.fetchStorageDevices (app://./index.bundle.js:1:48802)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async o.mounted (app://./index.bundle.js:1:22620)

Thanks for this discovery
Ted

**Comment by OfficialEsco** [comment] 2021-05-26 15:09
Duplicate of #1
This will be fixed in the next release

**Closed** 2021-05-26 15:32 UTC
